import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import NavThing from "@/components/NavThing";
import {Toaster} from "@/components/ui/toaster";
import 'dotenv'

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {


  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,

}: {
  children: React.ReactNode,

}) {



  return (
    <html lang="en">

      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
      )} ><NavThing></NavThing>{children}<Toaster /></body>


    </html>
  )
}
